In [ ]:
import torch
import torch.nn as nn
import numpy as np

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        # Convolutional layer:
        # in_channels=1 for grayscale input, out_channels=16 (you can change this), kernel_size=3,
        # stride=1, and padding=1 to keep the spatial dimensions the same (32x32)
        self.conv = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, stride=1, padding=1)
        
        # Max pooling layer: kernel_size=2 and stride=2 reduce the spatial dimensions by half.
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Leaky ReLU activation:
        self.leaky_relu = nn.LeakyReLU(negative_slope=0.01)

    def forward(self, x):
        # Pass input through convolutional layer
        x = self.conv(x)
        # Then apply max pooling
        x = self.pool(x)
        # Finally apply Leaky ReLU activation
        x = self.leaky_relu(x)
        return x

# Create an instance of the model
model = SimpleCNN()

# Access the convolutional layer weights
# model.conv.weight has the shape [out_channels, in_channels, kernel_height, kernel_width]
weights = model.conv.weight

# Convert the weights to a NumPy array
weights_np = weights.detach().cpu().numpy()

# Optionally, set NumPy print options to see the full array
np.set_printoptions(threshold=np.inf)

#这里打印kernel weight的数据
print("Convolutional layer weights as array:")
print(weights_np)



Convolutional layer weights as array:
[[[[-0.09960763 -0.13388002 -0.23404936]
   [-0.2340715   0.11863884  0.32374668]
   [-0.3034844  -0.32870957  0.15807423]]]


 [[[-0.27953917 -0.27944058 -0.10488296]
   [ 0.16874146 -0.17158517  0.29836676]
   [-0.06800728 -0.10459201  0.25236306]]]


 [[[ 0.22943597 -0.07500824 -0.229704  ]
   [-0.21415505  0.0390356   0.02073181]
   [ 0.2617341   0.00200693  0.00923622]]]


 [[[-0.06148505  0.19762123 -0.1767029 ]
   [ 0.17797518  0.22976863 -0.14487104]
   [ 0.04233023 -0.2905537   0.28979033]]]


 [[[ 0.12306003  0.16056764  0.20235388]
   [-0.23200183 -0.25433016  0.12601797]
   [ 0.29772887 -0.31880558 -0.1356347 ]]]


 [[[ 0.26729283 -0.21206681  0.10571023]
   [-0.17234051 -0.20477903  0.02398702]
   [ 0.06699109 -0.17629024 -0.01911326]]]


 [[[-0.12855038 -0.21778898  0.03911877]
   [ 0.26038927 -0.11525782  0.19137856]
   [-0.0907348  -0.0852209   0.08628055]]]


 [[[-0.29338402  0.0766993   0.08529186]
   [-0.00846227  0.0545404   0.2